In [46]:
import minitorch
import numpy as np

In [47]:
data = np.arange(0,3*4*5*6).reshape(3,4,5,6)
A_ = minitorch.tensor(data.tolist())

In [48]:
B_ = minitorch.nn.max(A_, 0)

In [49]:
B_.shape

(1, 4, 5, 6)

In [50]:
B_


[
	[
		[
			[240.00 241.00 242.00 243.00 244.00 245.00]
			[246.00 247.00 248.00 249.00 250.00 251.00]
			[252.00 253.00 254.00 255.00 256.00 257.00]
			[258.00 259.00 260.00 261.00 262.00 263.00]
			[264.00 265.00 266.00 267.00 268.00 269.00]]
		[
			[270.00 271.00 272.00 273.00 274.00 275.00]
			[276.00 277.00 278.00 279.00 280.00 281.00]
			[282.00 283.00 284.00 285.00 286.00 287.00]
			[288.00 289.00 290.00 291.00 292.00 293.00]
			[294.00 295.00 296.00 297.00 298.00 299.00]]
		[
			[300.00 301.00 302.00 303.00 304.00 305.00]
			[306.00 307.00 308.00 309.00 310.00 311.00]
			[312.00 313.00 314.00 315.00 316.00 317.00]
			[318.00 319.00 320.00 321.00 322.00 323.00]
			[324.00 325.00 326.00 327.00 328.00 329.00]]
		[
			[330.00 331.00 332.00 333.00 334.00 335.00]
			[336.00 337.00 338.00 339.00 340.00 341.00]
			[342.00 343.00 344.00 345.00 346.00 347.00]
			[348.00 349.00 350.00 351.00 352.00 353.00]
			[354.00 355.00 356.00 357.00 358.00 359.00]]]]

In [52]:
B_.backward(B_)

In [54]:
A_.grad.shape

(3, 4, 5, 6)